[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LAMDA-TALENT"
authors = [{name = "Siyang Liu", email = "liusy@lamda.nju.edu.cn"}]
dynamic = ["version", "description"]
